# Exercise to compile examples
# Using a common build setup for all exercises

TOP_DIR=../../../
include ${TOP_DIR}/common/vars.mak

TARGETS=main${EXE}

all  : ${TARGETS}

main${EXE} : ${OBJ_DIR}/engine_cylinder.o

include ${TOP_DIR}/common/targets.mak
